[package]
name = "howto-cli"
version = "0.1.0"
authors = ["pbzweihander <sd852456@naver.com>"]
license = "MIT"
description = "instant coding answers via the command line"
repository = "https://github.com/pbzweihander/howto"
keywords = ["cli", "search"]

[dependencies]
howto = { version = "*", path = "../howto" }

[[bin]]
name = "howto"
path = "src/main.rs"