version: 2

docker_login: &docker_login
  run:
    name: authentication
    command: |
      docker --version
      docker-compose --version
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
cargo_login: &cargo_login
  run:
    name: authentication
    command:  |
      cargo --version
      cargo login "$CARGO_TOKEN"

workflows:
  version: 2
  flow:
    jobs:
      - test
      - lib_publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - lib_publish
      - bin_publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - docker_push:
          requires:
            - build
          filters:
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: clux/muslrust
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - lib-target-{{ checksum "howto/Cargo.toml" }}
          - lib-target-
      - run:
          working_directory: howto
          command: cargo test
      - save_cache:
          key: lib-target-{{ checksum "howto/Cargo.toml" }}
          paths:
            - howto/target
  build:
    docker:
      - image: clux/muslrust
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - bin-target-{{ checksum "howto-cli/Cargo.lock" }}
          - bin-target-
      - run:
          working_directory: howto-cli
          command: cargo build --release
      - save_cache:
          key: bin-target-{{ checksum "howto-cli/Cargo.lock" }}
          paths:
            - howto-cli/target
      - run: mv howto-cli/target/x86_64-unknown-linux-musl/release/howto howto-cli/
      - persist_to_workspace:
          root: .
          paths:
            - howto-cli/howto
  docker_push:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - <<: *docker_login
      - run: make docker-push
  lib_publish:
    docker:
      - image: clux/muslrust
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - lib-target-{{ checksum "howto/Cargo.toml" }}
          - lib-target-
      - <<: *cargo_login
      - run: curl -sSL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 --output /usr/bin/jq
      - run: chmod +x /usr/bin/jq
      - run: make lib-publish
  bin_publish:
    docker:
      - image: clux/muslrust
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - bin-target-{{ checksum "howto/Cargo.toml" }}
          - bin-target-
      - <<: *cargo_login
      - run: curl -sSL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 --output /usr/bin/jq
      - run: chmod +x /usr/bin/jq
      - run: make bin-publish
