version: 2

workflows:
  version: 2
  flow:
    jobs:
      - test
      - build

jobs:
  test:
    docker:
      - image: clux/muslrust:stable-2019-12-21
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - &lib-cache-key lib-v1-{{ checksum "howto/Cargo.toml" }}
          - lib-v1-
      - run:
          command: cargo check --all-targets
      - run:
          command: cargo test
      - save_cache:
          key: *lib-cache-key
          paths:
            - /root/.cargo/registry
            - target/x86_64-unknown-linux-musl/debug/deps
            - target/x86_64-unknown-linux-musl/debug/build
  build:
    docker:
      - image: clux/muslrust:stable-2019-12-21
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - &bin-cache-key bin-v1-{{ checksum "howto-cli/Cargo.lock" }}
          - bin-v1-
      - run:
          command: cargo build --release
      - save_cache:
          key: *bin-cache-key
          paths:
            - /root/.cargo/registry
            - target/x86_64-unknown-linux-musl/debug/deps
            - target/x86_64-unknown-linux-musl/debug/build
      - run: mv target/x86_64-unknown-linux-musl/release/howto-cli howto-cli/howto
      - persist_to_workspace:
          root: .
          paths:
            - howto-cli/howto
