[package]
name = "howto"
version = "0.1.0"
authors = ["pbzweihander <sd852456@naver.com>"]
license = "MIT"
description = "instant coding answers via the command line"
repository = "https://github.com/pbzweihander/howto"
keywords = ["cli", "search"]

[dependencies]
scraper = "0.7"
failure = "0.1"
lazy_static = "1.1"
hyper = "0.12"
hyper-tls = "0.3"
futures = "0.1"
tokio = "0.1"
slugify = "0.1"
